map_type: costmap

obstacle_range: 6
raytrace_range: 7

footprint: [ [-0.2, -0.25], [-0.2, 0.3], [0.2, 0.3], [0.2, -0.25] ]

transform_tolerance: 1.0

robot_radius: 0.25
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mcl_bot/laser/scan, marking: true, clearing: true}
